In [137]:
import numpy as np
import pandas as pd

In [99]:
data1=np.round(np.random.normal(np.random.randint(1,100,1),2.0,(100,8)),1)
data2=data1.T@data1

In [100]:
data2

array([[374980.41, 373747.05, 373000.73, 373518.38, 372988.93, 375070.87,
        374917.13, 373900.06],
       [373747.05, 373568.03, 372298.4 , 372847.28, 372293.89, 374436.58,
        374231.2 , 373186.98],
       [373000.73, 372298.4 , 371948.78, 372076.04, 371510.7 , 373615.58,
        373455.23, 372524.67],
       [373518.38, 372847.28, 372076.04, 373069.55, 372098.01, 374156.7 ,
        373997.86, 373092.03],
       [372988.93, 372293.89, 371510.7 , 372098.01, 372015.25, 373640.43,
        373477.39, 372480.26],
       [375070.87, 374436.58, 373615.58, 374156.7 , 373640.43, 376130.93,
        375550.05, 374555.81],
       [374917.13, 374231.2 , 373455.23, 373997.86, 373477.39, 375550.05,
        375904.89, 374432.43],
       [373900.06, 373186.98, 372524.67, 373092.03, 372480.26, 374555.81,
        374432.43, 373810.27]])

In [101]:
np.linalg.matrix_rank(data2)

8

In [102]:
infor1=np.linalg.eig(data2)

In [103]:
len(np.unique(infor1[0]))

8

In [104]:
infor1[1].shape

(8, 8)

In [133]:
data4=np.round(np.random.normal(np.random.randint(1,100,1),2.0,(100,100)),1)
np.linalg.matrix_rank(data4)

100

In [134]:
infor2=np.linalg.eig(data4)

In [135]:
len(np.unique(infor2[0]))

100

In [139]:
data = pd.read_excel(r'principal_component.xls', header = None)
from sklearn.decomposition import PCA
pca=PCA(3,whiten=True)
pca.fit(data)

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
  svd_solver='auto', tol=0.0, whiten=True)

In [140]:
dimension_reduce=pca.transform(data)
whitening=dimension_reduce

whitening

array([[ 0.4092006 ,  1.87527696,  0.8310095 ],
       [ 0.01425095, -0.71895297, -0.98378133],
       [-1.18430954, -0.31644215, -0.10553066],
       [-0.72095604,  0.25506268, -0.31938734],
       [ 0.27128003,  1.11014802,  2.02355866],
       [ 1.20689773, -1.03884292,  0.15442648],
       [-0.1829036 , -0.84333921, -0.5025276 ],
       [ 0.69775609,  1.54104821, -1.37070358],
       [ 2.04221893, -1.47067143,  0.88530976],
       [-0.08736564, -0.4693868 , -0.12535778],
       [-1.09617986, -0.26252712,  0.28311046],
       [-1.83379272, -0.6662154 ,  0.84417097],
       [ 0.16422834,  0.53957487,  0.21344191],
       [ 0.29967472,  0.46526723, -1.82773945]])

In [141]:
np.var(whitening,axis=0)

array([0.92857143, 0.92857143, 0.92857143])

In [142]:
pca=PCA(3)
pca.fit(data)

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [143]:
dimension_reduce=pca.transform(data)
Ohne_Whitening=dimension_reduce

Ohne_Whitening

array([[  8.19133694,  16.90402785,   3.90991029],
       [  0.28527403,  -6.48074989,  -4.62870368],
       [-23.70739074,  -2.85245701,  -0.4965231 ],
       [-14.43202637,   2.29917325,  -1.50272151],
       [  5.4304568 ,  10.00704077,   9.52086923],
       [ 24.15955898,  -9.36428589,   0.72657857],
       [ -3.66134607,  -7.60198615,  -2.36439873],
       [ 13.96761214,  13.89123979,  -6.44917778],
       [ 40.88093588, -13.25685287,   4.16539368],
       [ -1.74887665,  -4.23112299,  -0.58980995],
       [-21.94321959,  -2.36645883,   1.33203832],
       [-36.70868069,  -6.00536554,   3.97183515],
       [  3.28750663,   4.86380886,   1.00424688],
       [  5.99885871,   4.19398863,  -8.59953736]])

In [145]:
np.var(Ohne_Whitening,axis=0)

array([372.09375398,  75.45097903,  20.55592011])

In [149]:
pca.explained_variance_

array([400.71635044,  81.25490049,  22.13714474])

In [150]:
Ohne_Whitening/np.sqrt(pca.explained_variance_)

array([[ 0.4092006 ,  1.87527696,  0.8310095 ],
       [ 0.01425095, -0.71895297, -0.98378133],
       [-1.18430954, -0.31644215, -0.10553066],
       [-0.72095604,  0.25506268, -0.31938734],
       [ 0.27128003,  1.11014802,  2.02355866],
       [ 1.20689773, -1.03884292,  0.15442648],
       [-0.1829036 , -0.84333921, -0.5025276 ],
       [ 0.69775609,  1.54104821, -1.37070358],
       [ 2.04221893, -1.47067143,  0.88530976],
       [-0.08736564, -0.4693868 , -0.12535778],
       [-1.09617986, -0.26252712,  0.28311046],
       [-1.83379272, -0.6662154 ,  0.84417097],
       [ 0.16422834,  0.53957487,  0.21344191],
       [ 0.29967472,  0.46526723, -1.82773945]])