In [38]:
import numpy as np
import pandas as pd
from sklearn.feature_selection import VarianceThreshold
from scipy.stats import f

In [2]:
np.random.seed(4)
X = np.random.randint(6,8,(300,5))
X_fr=pd.DataFrame(X)
X_fr[X_fr[0]==6]=7
selector=VarianceThreshold(threshold=(0.05))
selector.fit_transform(X)#建议阈值为0.05左右

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       ...,
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 6]])

In [3]:
selector.variances_

array([0.        , 0.21      , 0.20305556, 0.20728889, 0.2016    ])

In [4]:
X_fr.describe()

0           1           2           3           4
count  300.0  300.000000  300.000000  300.000000  300.000000
mean     7.0    6.700000    6.716667    6.706667    6.720000
std      0.0    0.459023    0.451370    0.456051    0.449749
min      7.0    6.000000    6.000000    6.000000    6.000000
25%      7.0    6.000000    6.000000    6.000000    6.000000
50%      7.0    7.000000    7.000000    7.000000    7.000000
75%      7.0    7.000000    7.000000    7.000000    7.000000
max      7.0    7.000000    7.000000    7.000000    7.000000

In [6]:
from sklearn.feature_selection import f_regression
Data_01=np.random.rand()*np.random.randint(2,1000,(200,6))
f_regression(Data_01[:,0:5],Data_01[:,5])#返回f值和f-值的p值

(array([0.44398786, 1.03851596, 0.31914032, 0.15589646, 2.33403656]),
 array([0.50597956, 0.30941044, 0.57276423, 0.693388  , 0.12816918]))

In [10]:
Y1=(Data_01[:, 5] - np.mean(Data_01[:, 5],axis=0))
#关联系数
cor_1=[np.dot((Data_01[:, k] - np.mean(Data_01[:, k],axis=0))
        ,Y1)/(Data_01[:, k].std(0)*Data_01[:, 5].std(0)*len(Data_01[:, 5])) for k in range(5)]
#通常我们利用F-检验（F_value(1,n-2)）来检验正态假定下两个变量之间的相关性
F=((np.array(cor_1)**2)/(1-(np.array(cor_1)**2)))*(len(Data_01[:, 5])-2)
F

array([0.44398786, 1.03851596, 0.31914032, 0.15589646, 2.33403656])

In [9]:
p=[]
for k in F:
     p.append(1-f.cdf(k,1,len(Data_01[:, 5])-2))
p

[0.5059795615561491,
 0.30941043833696547,
 0.5727642294156681,
 0.6933879956863616,
 0.12816917757410518]

In [36]:
len(Data_01[:, 5])

200

In [30]:
from sklearn.datasets import load_diabetes
dia_data=load_diabetes()

In [31]:
dia_data.data.shape

(442, 10)

In [42]:
f_regression(dia_data.data,dia_data.target)

(array([ 16.10137401,   0.81742349, 230.65376449, 106.52138379,
         20.71056745,  13.74607917,  81.23965868, 100.06926441,
        207.27209108,  75.3996832 ]),
 array([7.05568615e-05, 3.66429295e-01, 3.46600645e-42, 1.64853275e-22,
        6.92071179e-06, 2.35984810e-04, 6.16286470e-18, 2.30425328e-21,
        8.82375416e-39, 7.58008327e-17]))

In [33]:
Y1=(dia_data.target - np.mean(dia_data.target,axis=0))
#关联系数
cor_1=[np.dot((dia_data.data[:, k] - np.mean(dia_data.data[:, k],axis=0))
        ,Y1)/(dia_data.data[:, k].std(0)*dia_data.target.std(0)*len(dia_data.target)) for k in range(10)]
#通常我们利用F-检验（F_value(1,n-2)）来检验正态假定下两个变量之间的相关性
F1=((np.array(cor_1)**2)/(1-(np.array(cor_1)**2)))*(len(dia_data.data)-2)
F1

array([ 16.10137401,   0.81742349, 230.65376449, 106.52138379,
        20.71056745,  13.74607917,  81.23965868, 100.06926441,
       207.27209108,  75.3996832 ])

In [52]:
from sklearn.feature_selection import f_classif
from sklearn.datasets import load_breast_cancer
cancer_data=load_breast_cancer()
f_classif(cancer_data.data,cancer_data.target)

(array([6.46981021e+02, 1.18096059e+02, 6.97235272e+02, 5.73060747e+02,
        8.36511234e+01, 3.13233079e+02, 5.33793126e+02, 8.61676020e+02,
        6.95274435e+01, 9.34592949e-02, 2.68840327e+02, 3.90947023e-02,
        2.53897392e+02, 2.43651586e+02, 2.55796780e+00, 5.32473391e+01,
        3.90144816e+01, 1.13262760e+02, 2.41174067e-02, 3.46827476e+00,
        8.60781707e+02, 1.49596905e+02, 8.97944219e+02, 6.61600206e+02,
        1.22472880e+02, 3.04341063e+02, 4.36691939e+02, 9.64385393e+02,
        1.18860232e+02, 6.64439606e+01]),
 array([8.46594057e-096, 4.05863605e-025, 8.43625104e-101, 4.73456431e-088,
        1.05185036e-018, 3.93826311e-056, 9.96655576e-084, 7.10115016e-116,
        5.73338403e-016, 7.59936804e-001, 9.73894866e-050, 8.43332029e-001,
        1.65190518e-047, 5.89552139e-046, 1.10296609e-001, 9.97599465e-013,
        8.26017617e-010, 3.07230877e-024, 8.76641818e-001, 6.30735508e-002,
        8.48229192e-116, 1.07805749e-030, 5.77139714e-119, 2.82884770e-097

In [63]:
cancer_data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [64]:
Y1=(cancer_data.target - np.mean(cancer_data.target,axis=0))
#关联系数
cor_1=[np.dot((cancer_data.data[:, k] - np.mean(cancer_data.data[:, k],axis=0))
        ,Y1)/(cancer_data.data[:, k].std(0)*cancer_data.target.std(0)*len(cancer_data.target)) for k in range(30)]
#通常我们利用F-检验（F_value(1,n-2)）来检验正态假定下两个变量之间的相关性
F1=((np.array(cor_1)**2)/(1-(np.array(cor_1)**2)))*(len(cancer_data.data)-2)
F1

array([6.46981021e+02, 1.18096059e+02, 6.97235272e+02, 5.73060747e+02,
       8.36511234e+01, 3.13233079e+02, 5.33793126e+02, 8.61676020e+02,
       6.95274435e+01, 9.34592949e-02, 2.68840327e+02, 3.90947023e-02,
       2.53897392e+02, 2.43651586e+02, 2.55796780e+00, 5.32473391e+01,
       3.90144816e+01, 1.13262760e+02, 2.41174067e-02, 3.46827476e+00,
       8.60781707e+02, 1.49596905e+02, 8.97944219e+02, 6.61600206e+02,
       1.22472880e+02, 3.04341063e+02, 4.36691939e+02, 9.64385393e+02,
       1.18860232e+02, 6.64439606e+01])

In [57]:
#array([6.46981021e+02, 1.18096059e+02, 6.97235272e+02, 5.73060747e+02,
        #8.36511234e+01, 3.13233079e+02, 5.33793126e+02, 8.61676020e+02,
        #6.95274435e+01, 9.34592949e-02, 2.68840327e+02, 3.90947023e-02,
        #2.53897392e+02, 2.43651586e+02, 2.55796780e+00, 5.32473391e+01,
        #3.90144816e+01, 1.13262760e+02, 2.41174067e-02, 3.46827476e+00,
        #8.60781707e+02, 1.49596905e+02, 8.97944219e+02, 6.61600206e+02,
        #1.22472880e+02, 3.04341063e+02, 4.36691939e+02, 9.64385393e+02,
        #1.18860232e+02, 6.64439606e+01]),

In [8]:
from sklearn.datasets import load_iris,load_breast_cancer,load_linnerud
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
#纸鸢花数据集
iris = load_iris()
X, y = iris.data, iris.target
print(X.shape)
colhr=SelectKBest(chi2, k=2).fit_transform(X, y)#选择与y值最相关的三个列
print(colhr)

(150, 4)
[[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [1.7 0.4]
 [1.4 0.3]
 [1.5 0.2]
 [1.4 0.2]
 [1.5 0.1]
 [1.5 0.2]
 [1.6 0.2]
 [1.4 0.1]
 [1.1 0.1]
 [1.2 0.2]
 [1.5 0.4]
 [1.3 0.4]
 [1.4 0.3]
 [1.7 0.3]
 [1.5 0.3]
 [1.7 0.2]
 [1.5 0.4]
 [1.  0.2]
 [1.7 0.5]
 [1.9 0.2]
 [1.6 0.2]
 [1.6 0.4]
 [1.5 0.2]
 [1.4 0.2]
 [1.6 0.2]
 [1.6 0.2]
 [1.5 0.4]
 [1.5 0.1]
 [1.4 0.2]
 [1.5 0.2]
 [1.2 0.2]
 [1.3 0.2]
 [1.4 0.1]
 [1.3 0.2]
 [1.5 0.2]
 [1.3 0.3]
 [1.3 0.3]
 [1.3 0.2]
 [1.6 0.6]
 [1.9 0.4]
 [1.4 0.3]
 [1.6 0.2]
 [1.4 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [4.7 1.4]
 [4.5 1.5]
 [4.9 1.5]
 [4.  1.3]
 [4.6 1.5]
 [4.5 1.3]
 [4.7 1.6]
 [3.3 1. ]
 [4.6 1.3]
 [3.9 1.4]
 [3.5 1. ]
 [4.2 1.5]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]
 [4.4 1.4]
 [4.5 1.5]
 [4.1 1. ]
 [4.5 1.5]
 [3.9 1.1]
 [4.8 1.8]
 [4.  1.3]
 [4.9 1.5]
 [4.7 1.2]
 [4.3 1.3]
 [4.4 1.4]
 [4.8 1.4]
 [5.  1.7]
 [4.5 1.5]
 [3.5 1. ]
 [3.8 1.1]
 [3.7 1. ]
 [3.9 1.2]
 [5.1 1.6]
 [4.5 1.5]
 [4.5 1.6]
 [4.7 1.5]
 [4.4 1.3]
 [4.1 1.3]
 [4.  1.3]
 

In [16]:
lbc=load_breast_cancer()
X1, y1 = lbc.data, lbc.target
print(X1.shape)
colhr1=SelectKBest(chi2, k=1).fit_transform(X1, y1)#选择与y值最相关的7个列
colhr1[1:3]

(569, 30)


array([[1956.],
       [1709.]])

In [22]:
tnx = load_linnerud()
X2, y2= tnx.data, tnx.target
#print(X2.shape,y2.shape)
colhr2=SelectKBest(chi2, k=2).fit_transform(X2, y2[:,0:1])#选择与y值最相关的2个列
print(colhr2)

[[162.  60.]
 [110.  60.]
 [101. 101.]
 [105.  37.]
 [155.  58.]
 [101.  42.]
 [101.  38.]
 [125.  40.]
 [200.  40.]
 [251. 250.]
 [120.  38.]
 [210. 115.]
 [215. 105.]
 [ 50.  50.]
 [ 70.  31.]
 [210. 120.]
 [ 60.  25.]
 [230.  80.]
 [225.  73.]
 [110.  43.]]


In [18]:
tnx

{'data': array([[  5., 162.,  60.],
        [  2., 110.,  60.],
        [ 12., 101., 101.],
        [ 12., 105.,  37.],
        [ 13., 155.,  58.],
        [  4., 101.,  42.],
        [  8., 101.,  38.],
        [  6., 125.,  40.],
        [ 15., 200.,  40.],
        [ 17., 251., 250.],
        [ 17., 120.,  38.],
        [ 13., 210., 115.],
        [ 14., 215., 105.],
        [  1.,  50.,  50.],
        [  6.,  70.,  31.],
        [ 12., 210., 120.],
        [  4.,  60.,  25.],
        [ 11., 230.,  80.],
        [ 15., 225.,  73.],
        [  2., 110.,  43.]]),
 'feature_names': ['Chins', 'Situps', 'Jumps'],
 'target': array([[191.,  36.,  50.],
        [189.,  37.,  52.],
        [193.,  38.,  58.],
        [162.,  35.,  62.],
        [189.,  35.,  46.],
        [182.,  36.,  56.],
        [211.,  38.,  56.],
        [167.,  34.,  60.],
        [176.,  31.,  74.],
        [154.,  33.,  56.],
        [169.,  34.,  50.],
        [166.,  33.,  52.],
        [154.,  34.,  64.],
        

In [30]:
?pd.dcor

Object `pd.dcor` not found.


In [77]:
import numpy as np
from scipy import linalg
import pandas as pd
def dist_corr(x,y):#如果x,y是二维数组，应通过行矢量形成距离矩阵
    col=x.shape[0]
    a=np.zeros((col,col))
    b=np.zeros((col,col))
    A=np.zeros((col,col))
    B=np.zeros((col,col))
    for j in range(col):
        for k in range(col):
            a[j,k]=linalg.norm(x[j]-x[k])
            b[j,k]=linalg.norm(y[j]-y[k])
    #print(a,a.shape,b,b.shape)
    for m in  range(col):
        for n in range(col):
            A[m,n]=a[m,n]-a[m].mean()-a[:,n].mean()+a.mean()
            B[m,n]=b[m,n]-b[m].mean()-b[:,n].mean()+b.mean()
    cov_xy=np.sqrt((1/(col**2))*((A*B).sum()))
    cov_xx=np.sqrt((1/(col**2))*((A*A).sum()))
    cov_yy=np.sqrt((1/(col**2))*((B*B).sum()))
    return cov_xy/np.sqrt(cov_xx*cov_yy)

In [78]:
from scipy.stats import pearsonr
X=np.random.randint(-100,100,200)*0.1
X=X.reshape(len(X),1)

In [79]:
X[2]

array([-1.6])

In [80]:
Y=X**2
#print(pearsonr(X,Y))
print(dist_corr(X,Y))

0.5115768180767845


In [84]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
boston = load_boston()
#波士顿房价数据集
X = boston["data"]
Y = boston["target"]
names = boston["feature_names"]
lr = LinearRegression()
rfe = RFE(lr, n_features_to_select=1)
#创建rfe模型
rfe.fit(X,Y)
#训练rfe模型
print(names)
rfe.support_,rfe.ranking_



['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


(array([False, False, False, False,  True, False, False, False, False,
        False, False, False, False]),
 array([ 8, 10,  9,  3,  1,  2, 13,  5,  7, 11,  4, 12,  6]))

In [86]:
list(zip(list(rfe.ranking_),list(names)))

[(8, 'CRIM'),
 (10, 'ZN'),
 (9, 'INDUS'),
 (3, 'CHAS'),
 (1, 'NOX'),
 (2, 'RM'),
 (13, 'AGE'),
 (5, 'DIS'),
 (7, 'RAD'),
 (11, 'TAX'),
 (4, 'PTRATIO'),
 (12, 'B'),
 (6, 'LSTAT')]

In [87]:
sorted(zip(list(rfe.ranking_),list(names)))

[(1, 'NOX'),
 (2, 'RM'),
 (3, 'CHAS'),
 (4, 'PTRATIO'),
 (5, 'DIS'),
 (6, 'LSTAT'),
 (7, 'RAD'),
 (8, 'CRIM'),
 (9, 'INDUS'),
 (10, 'ZN'),
 (11, 'TAX'),
 (12, 'B'),
 (13, 'AGE')]

In [89]:
boston['DESCR']

".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000