In [21]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
#高斯模型
iris = datasets.load_iris()
Xtrain,Xtest,ytrain,ytest=train_test_split(iris.data,iris.target,test_size=0.15)
gnb = GaussianNB().fit(Xtrain,ytrain)
gnb.predict(Xtest)
gnb.score(Xtest,ytest)
gnb.class_prior_

array([0.33858268, 0.33070866, 0.33070866])

In [5]:
gnb.predict([iris.data[134]])

array([2])

In [7]:
#对新数据预测
sdf=np.array([6,4,6,3])
gnb.predict([sdf])


array([2])

In [9]:
sdf1=np.array([5.1, 4.6, 1.1, 0.4])   
gnb.predict([sdf1])

array([0])

In [24]:
#预测很合理

#多项式模型
import numpy as np
X = np.random.randint(5, size=(6, 50))
y = np.array([1, 2, 3, 4, 5, 6])
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X, y)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [11]:
clf.predict([X[2]])

array([3])

In [26]:
#伯努利模型

X = np.random.randint(2, size=(10, 150))
Y = np.array([1,2,2,4,3,4,4,3,2,1])
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB()
clf.fit(X, Y)
BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)
clf.predict([X[2]])

array([2])

In [13]:
X

array([[0, 0, 1, ..., 0, 0, 0],
       [1, 1, 0, ..., 1, 1, 0],
       [0, 1, 0, ..., 0, 0, 1],
       ...,
       [1, 1, 0, ..., 1, 1, 1],
       [0, 0, 1, ..., 0, 0, 1],
       [0, 1, 0, ..., 1, 0, 0]])

In [56]:
data_n=pd.read_excel(r'C:\Users\leadlu\Desktop\discrete data for bayes.xls',sheet_name='Sheet2',header=None).values
data_n

array([[ 1,  1,  0,  0, -1],
       [ 1,  0,  1,  0, -1],
       [ 1,  0,  1,  0,  1],
       [ 1,  1,  0,  0,  1],
       [ 1,  1,  0,  0, -1],
       [ 2,  1,  0,  0, -1],
       [ 2,  0,  1,  0, -1],
       [ 2,  0,  1,  0,  1],
       [ 2,  0,  0,  1,  1],
       [ 2,  0,  0,  1,  1],
       [ 3,  0,  0,  1,  1],
       [ 3,  0,  1,  0,  1],
       [ 3,  0,  1,  0,  1],
       [ 3,  0,  0,  1,  1],
       [ 3,  0,  0,  1, -1]], dtype=int64)

In [57]:
from sklearn.naive_bayes import MultinomialNB
ds_model = MultinomialNB()
ds_model.fit(data_n[:,0:4],data_n[:,4])

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [69]:
ds_model.predict(np.array([[2,0,0,1]]))

array([1], dtype=int64)

In [60]:
data_n[:,2]

array([0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0], dtype=int64)